### ISSUE TITLE
Failed to activate package: Missing /

### ISSUE THREAD

**Issue by pleonex** [jesseweed/seti-ui#303]
1. Change from One Light them to Seti

**Atom Version**: 1.8.0-beta4
**System**: "Fedora release
**Thrown From**: [seti-ui](https://github.com/jesseweed/seti-ui) package, v1.2.3
### Stack Trace

Failed to activate the seti-ui package

```
At Invalid regular expression: missing /

SyntaxError: Invalid regular expression: missing /
    at Module._compile (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .coffee] (/usr/local/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/benito/.atom/packages/seti-ui/lib/settings.coffee:1:7)
    at Object.<anonymous> (/home/benito/.atom/packages/seti-ui/lib/settings.coffee:1:1)
    at Module._compile (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/local/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/home/benito/.atom/packages/seti-ui/lib/main.coffee:3:5)
    at ThemePackage.module.exports.Package.activateNow (/usr/local/share/atom-beta/resources/app.asar/src/package.js:183:20)
    at /usr/local/share/atom-beta/resources/app.asar/src/theme-package.js:46:28
    at ThemePackage.module.exports.Package.measure (/usr/local/share/atom-beta/resources/app.asar/src/package.js:92:15)
    at /usr/local/share/atom-beta/resources/app.asar/src/theme-package.js:42:24
    at ThemePackage.module.exports.ThemePackage.activate (/usr/local/share/atom-beta/resources/app.asar/src/theme-package.js:38:97)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/local/share/atom-beta/resources/app.asar/src/package-manager.js:538:21)
    at /usr/local/share/atom-beta/resources/app.asar/src/theme-manager.js:332:52
    at /usr/local/share/atom-beta/resources/app.asar/src/config.js:614:16
    at /usr/local/share/atom-beta/resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/local/share/atom-beta/resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/usr/local/share/atom-beta/resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/usr/local/share/atom-beta/resources/app.asar/src/config.js:227:14)
    at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/usr/local/share/atom-beta/resources/app.asar/node_modules/settings-view/lib/themes-panel.js:527:28)
    at /usr/local/share/atom-beta/resources/app.asar/node_modules/settings-view/lib/themes-panel.js:534:24
```
### Commands

```
     -2:19.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-python-pep8",
      "spell-check",
      "markdown-toc",
      "linter-python-pep257",
      "minimap-autohide",
      "line-ending-converter",
      "omnisharp-atom",
      "imdone-atom",
      "imdone-atom-github",
      "term3",
      "todo-manager"
    ],
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-yeoman, v0.3.15
autocomplete-clang, v0.9.3
autocomplete-emojis, v2.5.0
autocomplete-python, v1.7.4
autocomplete-xml, v0.8.1
bottom-dock, v0.4.4
docblockr, v0.7.3
editor-stats, v0.17.0
file-icons, v1.7.13
git-log, v0.4.1
hex, v0.6.2
highlight-selected, v0.11.2
hyperclick, v0.0.36
language-arduino, v0.4.1
language-arm, v1.2.2
language-batchfile, v0.4.0
language-latex, v0.6.1
linter, v1.11.4
linter-clang, v3.4.4
linter-coffeelint, v1.1.2
linter-pep8, v1.3.0
merge-conflicts, v1.4.3
minimap, v4.24.3
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
pdf-view, v0.50.0
project-manager, v2.9.7
rest-client, v1.1.1
seti-ui, v1.2.3
symbols-tree-view, v0.13.2
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1
vue-autocomplete, v0.1.0
yuno-commit, v0.3.1

# Dev
No dev packages
```

**Comment by jesseweed** [comment]
Hmm, I can't seem to duplicate on Mac, may be a Fedora specific bug. I'll try and track down a copy of Fedora and see if I can repro.

**Comment by pleonex** [comment]
It's happening also for seti-sintax but not for other sintax or themes.

**Comment by pleonex** [comment]
I think this is the same as jesseweed/seti-syntax#122

**Comment by jesseweed** [comment]
I believe this should be fixed. Feel free to re-open if not.
