### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by gregkin** [jesseweed/seti-ui#415]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta3 x64
**Electron**: 1.3.14
**OS**: Microsoft Windows 10 Home
**Thrown From**: [seti-ui](https://github.com/jesseweed/seti-ui) package 1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\mrgre\.atom\packages\seti-ui\lib\headers.coffee:8

TypeError: Cannot read property '0' of undefined
    at updateTreeViewHeaderPosition (/packages/seti-ui/lib/headers.coffee:8:23)
    at /packages/seti-ui/lib/headers.coffee:29:5
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Project.module.exports.Project.removePath (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/project.js:322:1)
    at TreeView.module.exports.TreeView.removeProjectFolder (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/node_modules/tree-view/lib/tree-view.js:1248:1)
    at HTMLDivElement.atom.commands.add.tree-view:remove-project-folder (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/node_modules/tree-view/lib/tree-view.js:381:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/atom-environment.js:1292:1)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.17.0-beta3/resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:17 core:save (input.hidden-input)
     -4:04.8.0 core:delete (input.hidden-input)
  3x -4:03.1.0 core:backspace (input.hidden-input)
  2x -3:59.6.0 core:save (input.hidden-input)
     -3:55.2.0 core:delete (input.hidden-input)
  4x -3:52.8.0 core:backspace (input.hidden-input)
     -3:47 core:delete (input.hidden-input)
  2x -3:45.6.0 core:save (input.hidden-input)
     -3:30.6.0 core:delete (input.hidden-input)
  3x -3:28.7.0 core:backspace (input.hidden-input)
  2x -3:23.9.0 core:save (input.hidden-input)
     -3:19.3.0 core:delete (input.hidden-input)
  5x -3:17.6.0 core:backspace (input.hidden-input)
     -3:11.4.0 core:save (input.hidden-input)
  2x -2:48.8.0 core:delete (input.hidden-input)
     -0:13.7.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
atom-clock 0.1.7 
atom-file-icons 0.4.10 
atom-html-preview 0.1.22 
bliss-monokai-ui 0.2.0 
browser-plus 0.0.87 
climate-syntax 5.0.0 
climate-ui 4.5.1 
markdown-preview-plus-opener 0.2.0 
monokai-seti 0.7.0 
nucleus-dark-ui 0.11.17 
ruby-block 0.3.6 
set-syntax 0.3.2 
seti-syntax 1.1.3 
seti-ui 1.7.0 
toggle-gutter 0.3.3 
tomorrow-night-bright-syntax 0.1.0 
tree-view-autoresize-ide 1.5.0 
tree-view-bundler 0.0.3 
tree-view-full-width 0.1.0 
```

**Comment by jesseweed** [comment]
This should be fixed in the 1.9 release. Please let me know if you still experience the issue after updating. Thanks!
