### ISSUE TITLE
gulp tasks fail

### ISSUE THREAD

**Issue by mateodelnorte** [jesseweed/seti-ui#582]
Hi there. Thanks for this library. It's really great content. 

I'm having trouble running any of the referenced gulp tasks, using both node v12 and v14: 

```
$ gulp icon
(node:40249) V8: /Users/matt/development/asdfasdf/seti-ui-font/seti-ui/node_modules/ttf2woff2/jssrc/ttf2woff2.js:3 Invalid asm.js: Invalid member of stdlib
(Use `node --trace-warnings ...` to show where the warning was created)
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/matt/development/asdfasdf/seti-ui-font/seti-ui/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/matt/development/asfdasdf/seti-ui-font/seti-ui/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/matt/development/asdfasdf/seti-ui-font/seti-ui/gulpfile.js:24:6)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at requireOrImport (/Users/matt/n/lib/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/Users/matt/n/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/Users/matt/n/lib/node_modules/gulp/node_modules/gulp-cli/index.js:211:24)
    at Liftoff.execute (/Users/matt/n/lib/node_modules/gulp/node_modules/liftoff/index.js:201:12)
    at module.exports (/Users/matt/n/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/matt/n/lib/node_modules/gulp/node_modules/liftoff/index.js:191:5)
    at /Users/matt/n/lib/node_modules/gulp/node_modules/liftoff/index.js:149:9 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}```

Should these be running?

**Comment by mateodelnorte** [comment]
Note, ensuring I'm on the same version of gulp as is listed in package.json yields the following error: 

```
~/development/asdfasdf/seti-ui-font/seti-ui on  master! ⌚ 22:15:43
$ gulp icons
fs.js:40
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (/Users/matt/development/asdfasdf/seti-ui-font/seti-ui/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/matt/development/asdfasdf/seti-ui-font/seti-ui/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/matt/development/asdfasdf/seti-ui-font/seti-ui/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)

~/development/asdfasfd/seti-ui-font/seti-ui on  master! ⌚ 22:15:48
$ gulp --version
[22:15:59] CLI version 3.9.1
[22:15:59] Local version 3.9.1
```
